/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "add.h"
#include "unity_fixture.h"

TEST_GROUP_RUNNER(func_add) {
    RUN_TEST_CASE(func_add, zeros_should_add_to_zero); /* TEST_func_add_zeros_should_add_to_zero_ */
    RUN_TEST_CASE(func_add, zero_and_one_should_add_to_one); /* TEST_func_add_zero_and_one_should_add_to_one_ */
    RUN_TEST_CASE(func_add, one_and_zero_should_add_to_one); /* TEST_func_add_one_and_zero_should_add_to_one_ */
    RUN_TEST_CASE(func_add, one_and_two_should_add_to_three); /* TEST_func_add_one_and_two_should_add_to_three_ */
    RUN_TEST_CASE(func_add, two_and_three_should_add_to_five); /* TEST_func_add_two_and_three_should_add_to_five_ */
}
