/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "add.h"
#include "unity_fixture.h"

TEST_GROUP_RUNNER(add) {
    RUN_TEST_CASE(add, zeros_should_add_to_zero); /* TEST_add_zeros_should_add_to_zero_ */
    RUN_TEST_CASE(add, zero_and_one_should_add_to_one); /* TEST_add_zero_and_one_should_add_to_one_ */
    RUN_TEST_CASE(add, one_and_zero_should_add_to_one); /* TEST_add_one_and_zero_should_add_to_one_ */
    RUN_TEST_CASE(add, one_and_two_should_add_to_three); /* TEST_add_one_and_two_should_add_to_three_ */
    RUN_TEST_CASE(add, two_and_three_should_add_to_five); /* TEST_add_two_and_three_should_add_to_five_ */
}
